language: go

go:
- "1.12"

script: 
- go build
- tar czvf ddns.tar.gz ddns

deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "ddns.tar.gz"
  skip_cleanup: true
  on:
    tags: true