

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    go build
  displayName: 'build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'ddns'
    publishLocation: 'pipeline'